<?php

/**
 * @file
 * perso theme file.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function perso_preprocess_field(&$variables): void {

  // Ajout de l'index au champ entity_reference_revisions.
  if (isset($variables['element']['#field_type'])
    && $variables['element']['#field_type'] === 'entity_reference_revisions') {

    foreach($variables['items'] as $idx => $item) {
      $variables['items'][$idx]['content']['#paragraph']->index = $idx;
    }
  }
}