<?php

/**
 * @file
 * Primary module hooks for exmpl_article module.
 */

use Drupal\exmpl_article\Handler\ArticleThemeHandler;


/**
 * Implements hook_theme().
 */
function exmpl_article_theme($existing, $type, $theme, $path) {
  return [
    'custom_article_element' => [

    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function exmpl_article_preprocess_node__article(&$variables): void {
  /** @var ArticleThemeHandler $articleThemeHandler */
  $articleThemeHandler = Drupal::service('class_resolver')
    ->getInstanceFromDefinition(ArticleThemeHandler::class);

  $articleThemeHandler->setDrupalArticleVariables($variables);
}